# Generated by Django 5.2.3 on 2025-07-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='num',
            new_name='mn',
        ),
        migrations.RemoveField(
            model_name='person',
            name='fid',
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
