# Generated by Django 5.2.3 on 2025-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0002_rename_num_person_mn_remove_person_fid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mn', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
