# Generated by Django 5.2.3 on 2025-07-04 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0003_employe_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter valid mobile number', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('cpwd', models.CharField(max_length=100)),
            ],
        ),
    ]
