# Generated by Django 5.2.3 on 2025-07-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
